apiVersion: apps/v1
kind: Deployment
metadata:
  name: maddy
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: maddy
          image: maddy
          ports:
            - containerPort: 2525
              name: smtp
          volumeMounts:
            - name: maddy-config
              mountPath: /data/maddy.conf
              subPath: maddy.conf
            - name: maddy-data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
      volumes:
        - name: maddy-config
          configMap:
            name: maddy-config
        - name: maddy-data
          persistentVolumeClaim:
            claimName: maddy-data
