apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      component: maddy

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: maddy-config
    files:
      - maddy.conf
