hostname maddy.local

state_dir /data/state
runtime_dir /data/run

openmetrics tcp://0.0.0.0:9749 { }

target.remote outbound {
    limits {
        all rate 20 1s
        all concurrency 10
    }

    mx_auth {
        local_policy {
            min_tls_level none
            min_mx_level none
        }
    }
}

smtp tcp://0.0.0.0:2525 {
    hostname maddy.local
    tls off
    default_destination {
        deliver_to &outbound
    }
}
