apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app: oddbit-infra

resources:
  - keycloak
  - postgres
  - maddy
  - vault

images:
  - name: postgres
    newName: docker.io/postgres
    newTag: "18-alpine"
  - name: caddy
    newName: docker.io/caddy
    newTag: 2-alpine
  - name: maddy
    newName: docker.io/foxcpp/maddy
    newTag: "0.9"
  - name: openbao
    newName: docker.io/openbao/openbao
    newTag: "2.5"
  - name: bank-vaults
    newName: ghcr.io/bank-vaults/bank-vaults
    newTag: v1.32.1
  - name: keycloak
    newName: quay.io/keycloak/keycloak
    newTag: "26.5"
  - name: keycloak-config-cli
    newName: docker.io/adorsys/keycloak-config-cli
    newTag: 6.5.0-26.5.4
