apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      component: caddy

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - route.yaml

configMapGenerator:
  - files:
      - Caddyfile
    name: caddy-config
