apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      component: keycloak

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjobs/configure-keycloak.yaml

configMapGenerator:
  - name: keycloak-realm-config
    files:
      - config/keycloak.yaml
      - config/caara-races.yaml
      - config/oddbit.yaml
