realm: oddbit
enabled: true
displayName: oddbit.com authentication
verifyEmail: true
rememberMe: true
resetPasswordAllowed: true
loginWithEmailAllowed: true
registrationAllowed: true
actionTokenGeneratedByUserLifespan: 900
clientScopes:
  - name: groups
    protocol: openid-connect
    description: "Group membership"
    attributes:
      include.in.token.scope: "true"
      display.on.consent.screen: "true"
    protocolMappers:
      - name: group-membership
        protocol: openid-connect
        protocolMapper: oidc-group-membership-mapper
        consentRequired: false
        config:
          full.path: "false"
          introspection.token.claim: "true"
          userinfo.token.claim: "true"
          multivalued: "true"
          id.token.claim: "true"
          lightweight.claim: "false"
          access.token.claim: "true"
          claim.name: groups
defaultOptionalClientScopes:
  - groups
groups:
  - name: vault-admin
    path: /vault-admin
clients:
  - clientId: oddbit-vault
    rootUrl: https://vault.oddbit.com
    adminUrl: https://vault.oddbit.com
    baseUrl: https://vault.oddbit.com
    enabled: true
    alwaysDisplayInConsole: true
    clientAuthenticatorType: client-secret
    publicClient: false
    redirectUris:
      - https://vault.oddbit.com/ui/vault/auth/oidc/oidc/callback
      - http://localhost:8250/oidc/callback
    webOrigins:
      - https://vault.oddbit.com
    protocol: openid-connect
    protocolMappers:
      - name: oddbit-vault-audience
        protocol: openid-connect
        protocolMapper: oidc-audience-mapper
        consentRequired: false
        config:
          included.client.audience: oddbit-vault
          id.token.claim: "false"
          lightweight.claim: "false"
          introspection.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "false"
    defaultClientScopes:
      - web-origins
      - acr
      - profile
      - roles
      - basic
      - email
      - groups
    optionalClientScopes:
      - address
      - phone
      - offline_access
      - organization
      - microprofile-jwt
smtpServer:
  host: maddy
  port: "25"
  from: authadmin@oddbit.com
  fromDisplayName: Authentication Administrator
  ssl: "false"
  starttls: "false"
identityProviders:
  - alias: google
    displayName: Google
    providerId: google
    enabled: true
    updateProfileFirstLoginMode: "on"
    trustEmail: true
    storeToken: false
    addReadTokenRoleOnCreate: false
    authenticateByDefault: false
    linkOnly: false
    hideOnLogin: false
    config:
      acceptsPromptNoneForwardFromClient: "false"
      clientId: $(env:KEYCLOAK_GOOGLE_OAUTH_CLIENT_ID)
      disableUserInfo: "false"
      filteredByClaim: "false"
      syncMode: LEGACY
      clientSecret: "$(env:KEYCLOAK_GOOGLE_OAUTH_CLIENT_SECRET)"
      caseSensitiveOriginalUsername: "false"
      defaultScope: openid profile email
      guiOrder: "10"
